### ISSUE TITLE
Login keeps looping 

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/league-for-good#62]
Able to get the login screen, but then when I select my google userid it attempts to redirect to:

`http://localhost:4000/?code=4/XbD2kh3OWXu5K3O7HoXIrRjoQBb_yDycI6fcsmg--dk#`

That does not look like like my GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, SESSION_SECRET, or GOOGLE_CALLBACK_URL.

The loops back to login screen.

**Comment by paulywill** [comment]
I have:

GOOGLE_CALLBACK_URL=http://localhost:4000

I suspect that's wrong.. ?

**Comment by Jlevyd15** [comment]
I have a working setup and i'm using this:
``` GOOGLE_CALLBACK_URL = http://localhost:4000/auth/google/callback```

**Comment by paulywill** [comment]
Now I'm getting the following error:

  `Error
     at /Users/paulgamble/Coding/fcc/league-for-good/node_modules/passport-google-oauth20/lib/strategy.js:95:21
    at passBackControl (/Users/paulgamble/Coding/fcc/league-for-good/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/paulgamble/Coding/fcc/league-for-good/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by paulywill** [comment]
Referenced: https://github.com/freeCodeCamp/league-for-good/issues/54

@ajGingrich also suggested using mlab for mongodb uri was confused with

Forgot to run: **npm install**  before running **npm run dev**
